{% set name = "prawcore" %}
{% set version = "2.3.0" %}
{% set sha256 = "daf1ccd4b7a80dc4e6567d48336d782e94a9a6dad83770fc2edf76dc9a84f56d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests >=2.6.0,<3.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - prawcore

about:
  home: https://github.com/praw-dev/prawcore
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Low-level communication layer for PRAW 4+
  dev_url: https://github.com/praw-dev/prawcore

extra:
  recipe-maintainers:
    - CAM-Gerlach
    - djsutherland