travis:
  secure:
    BINSTAR_TOKEN: ibT0QgQyPo2b9/b2kJk+UI3JwAyVgTLV9TYKw3GHzCkyTmJW0Up4UgiL60cKZX3nrVnKCaK1i03UDZ6T+UtPrn7J+kHYZLfJxNsWszzIB9O72TLvwOeapQ7ou5OH2EsrQoHLCTt8FGpMNm1iNehKgaRi6hPK3bxh0p8iZLELaplIAxXlxP0K9L1kkqwivkfC6nKxgXUSf2Vf033PHCTzfPoe574mhBMHdMRMsDEIxYYPKdsYiO9Nl92VnrGWJqRD3DiiW05iSCww2XZKkIdWQWLQgODXdX34/hVO3qH4EdFf25b/B25EByykZV7Ojq27PqN8C+rL8RQST0Kfoi36VJac0Ri3TOB1LrbFZbVkZW7yDqvbxpniN7WuqC30tVYjDct/QzHW11Vdjqjh1Jn9v9NteEObQ3uK0wdvHz+VL2FGDD9PzE28zpj4fi9GHqRsTSV6cw9V3PKH3eEfrY27QIOnJ1ESTdq2cRZ7AQu90qhkPa5INlspEB5Vyw2BGcjo355LXwN5C1CGLByRDA9bPOeXqAfyfHUXrl6RrNJwFVX2YOBcqCwwpstgzAR1JVWC+4XzHoyWE2wBo8wRmluJwEMLxf0kM/ZoMWAS2gisugOt0YkZSHlzkEBIrB/T5IUvLWTQe8jd4WxPrL6sAlNqvshtmiXVXeR5NEOze7omm2U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
