travis:
  secure:
    BINSTAR_TOKEN: HpVYU3PIZ5PqMLwoGhTiJvXkQQMDfZ18XkEeL2ATsJHy9/uMHZLLXWapAR4QsTPUUBBXnv2jDeDJsj/QLxKjB3pxhUHnucBPunswaLILX7Kjpn/ADTvXusaee8JI9i4mkrvMWOCiS5XjYrIAzLxIqQsPmGvfa3J0c84DLo39pfga2Lzl7fkuAYOc6aKckw2EJBN734GOE8Y1Cg6ItKBZrIYfhTTM76xmNBrxVXI3LcwEoa9Ylwbgp3HsAcOIMrz4nGvYgPGOMCk4MF72QgNqErgAeokYJPLd5iB4xQ/o2sWm6m2R0nglMBnIUVsSgj7YPwRTornY0APAzHzhJuwbTaRTb25C8d3XlaNFZzs1EN3Hz8nAK3Pg74+DvXTsUazGYsSmnlAxtP6S0Q/5/X675m3SJOZbukHRaH+Qeoxp3kcfyDiS6Uued3qdV2xFykuQ4Ac1IwBj3gGxpSo4b37TLeeruzPh3C4Q1UYWXHkRkczixOszbZ9y8nlvWM+Qk3EK08EsPB9VVbQbjDeWhUix3ETVuyawYbH502pwOz05C9lFEmppK4v2CsFDpar4NUnfPNLBqkfBtJqHznjvYlk2s9fsjlxhmbr6hptVNHwhpsJonatBaEZykuf8AegikptHlymc62swhr8nWR0WP4uPG/+KP50dE7egkJlnPZRf4Ow=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
